

project:
  type: website

website:
  title: "DTSC691"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume
      - href: projects.qmd
        text: Projects
      - href: injury.qmd
        text: Injury Model

format:
  html:
    theme: 
      - sandstone
    css: styles.css
    toc: true

editor: source

